### PR TITLE
Fixes file name bug and adds various functionality

### LINKED ISSUE #3: Fails downloading half way through lists
Trying to get courses but get either of this  issues/warnings

Resizing Pixel by Pixel  
        wistiaVideoSize: 31195479
        existingFileSizeOnDisk: 31195479
        Full video file exists; moving to next lecture...

```
          Reshaping/Resizing Using the Space Bar

    wistiaVideoSize: 28745834       Downloading video ...
```

2015/05/24 07:36:34 open /Users/paulmellor/bitfountain-download-all-master/ios-design/2-Introduction-to-Sketch/12-Reshaping/Resizing-Using-the-Space-Bar.mp4: no such file or directory

have tried manual adding file but still fails in both errors

### PR DESCRIPTION
**Pull request by othyn**
fixes prateekbhatt/bitfountain-download-all#3

Adds / Changes:
    Adds a progress bar for the download
    Adds a new optional parameter ’-section’ to allow you to specify a
starting section for the download
    Formats the raw byte string into KB/MB for better readability
    Fixes issues with special characters within the filenames / folders

### CODE REVIEW

**Comment by othyn** [comment]
Damn, forgot to commit the binary as well. Ah well. :)

**Comment by PaulMellor** [comment]
Ok Seems to work for the Extra parameters.
As Well as the Section Parameter(Thanks)
 the Scrolling progress bar is a bit amusing but shows that it is still working.

**Comment by othyn** [comment]
The idea was that it just provides you, the user, with more information; current progress in KB/MB with a visual indicator / percentage, current download speed and time remaining. Upon completion it then shows the time it took to download. :)

**Comment by PaulMellor** [comment]
is there a way to keep it on the single line rather than a new line for each update, cause i do like the idea. but having it look like this is Amusing.
            News Feed: Introduction

```
    wistiaVideoSize: 12.8M
    Creating file ... Done!
    Downloading Video ... 
```

0 B / 12.76 MB [                                                       ] 0.00 % 93.43 KB / 12.76 MB [>                                 ] 0.72 % 186.41 KB/s 1m9s
160.93 KB / 12.76 MB [>                               ] 1.23 % 160.61 KB/s 1m20s
250.93 KB / 12.76 MB [>                               ] 1.92 % 166.84 KB/s 1m16s
336.71 KB / 12.76 MB [>                               ] 2.58 % 167.96 KB/s 1m15s
411.24 KB / 12.76 MB [=>                              ] 3.15 % 163.92 KB/s 1m17s
511.08 KB / 12.76 MB [=>                              ] 3.91 % 169.79 KB/s 1m13s
598.27 KB / 12.76 MB [=>                              ] 4.58 % 170.28 KB/s 1m13s
669.99 KB / 12.76 MB [=>                              ] 5.13 % 166.85 KB/s 1m14s
754.37 KB / 12.76 MB [=>                              ] 5.77 % 166.87 KB/s 1m13s
814.83 KB / 12.76 MB [=>                              ] 6.24 % 162.25 KB/s 1m15s
892.18 KB / 12.76 MB [==>                             ] 6.83 % 161.53 KB/s 1m15
s969.52 KB / 12.76 MB [==>                             ] 7.42 % 160.92 KB/s 1m15
s1.03 MB / 12.76 MB [==>                               ] 8.07 % 161.49 KB/s 1m14
s1.10 MB / 12.76 MB [==>                               ] 8.58 % 159.49 KB/s 1m14
s1.17 MB / 12.76 MB [===>                              ] 9.21 % 159.70 KB/s 1m14
s1.24 MB / 12.76 MB [===>

**Comment by othyn** [comment]
D'oh! I must have uploaded an old binary, I did fix that as I was going along, haha, it does look stupid...

**Comment by PaulMellor** [comment]
yeah updated binary but still causing the same issue.

**Comment by PaulMellor** [comment]
Only Issue i have had is it re-downloading files because it now either ignores following characters ' !? in the file names so can look funny the things such as file-s.

**Comment by othyn** [comment]
In regard to the first issue, are you running on windows? If so, I may know what the problem is with the script.

As to the second point, that is intentional. The regex strips out all special characters, just to avoid any possible errors across file systems.

**Comment by PaulMellor** [comment]
I am running OS X 10.10. And can live with loosing special characters.

**Comment by othyn** [comment]
Very odd. I'm running the same and it works fine. My assumption was that it would be odd behavior with the return character (\r), if under Windows, but I am thrown if you are also running it on 10.10. Hmm...

**Comment by PaulMellor** [comment]
I removed the \r from the progress bar and run it again this morning, Adjusting windows frame size and is now showing progress bar on a single line.

**Comment by othyn** [comment]
Strange... You see \r is the character for carriage return, and points the next line to be written back over the existing line, which gives the desired output - it overwriting the existing output onto the same line, effectively in this instance 'updating' the text.

I'll run a few tests and see why that is happening, specifically why me and you are having the opposite effects in removing and adding that character.

**Comment by prateekbhatt** [comment]
@othyn Thanks, and sorry for the delay, I've been busy with other work all this while

**Comment by othyn** [comment]
@prateekbhatt no worries man, thanks for the core application. Glad I could have helped! :)

**Pull request merged**
